# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created: Wed Jul  9 17:41:55 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 659)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doubleSpinBox_xres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_xres.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_xres.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_xres.setSizePolicy(sizePolicy)
        self.doubleSpinBox_xres.setMinimumSize(QtCore.QSize(101, 29))
        self.doubleSpinBox_xres.setMaximumSize(QtCore.QSize(101, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_xres.setFont(font)
        self.doubleSpinBox_xres.setDecimals(5)
        self.doubleSpinBox_xres.setMinimum(0.0)
        self.doubleSpinBox_xres.setMaximum(10000000.0)
        self.doubleSpinBox_xres.setObjectName("doubleSpinBox_xres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_xres)
        self.doubleSpinBox_yres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_yres.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_yres.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_yres.setSizePolicy(sizePolicy)
        self.doubleSpinBox_yres.setMinimumSize(QtCore.QSize(101, 28))
        self.doubleSpinBox_yres.setMaximumSize(QtCore.QSize(101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_yres.setFont(font)
        self.doubleSpinBox_yres.setDecimals(5)
        self.doubleSpinBox_yres.setMinimum(0.0)
        self.doubleSpinBox_yres.setMaximum(10000000.0)
        self.doubleSpinBox_yres.setObjectName("doubleSpinBox_yres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_yres)
        self.doubleSpinBox_zres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_zres.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_zres.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_zres.setSizePolicy(sizePolicy)
        self.doubleSpinBox_zres.setMinimumSize(QtCore.QSize(101, 28))
        self.doubleSpinBox_zres.setMaximumSize(QtCore.QSize(101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_zres.setFont(font)
        self.doubleSpinBox_zres.setDecimals(5)
        self.doubleSpinBox_zres.setMinimum(0.0)
        self.doubleSpinBox_zres.setMaximum(10000000.0)
        self.doubleSpinBox_zres.setObjectName("doubleSpinBox_zres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_zres)
        self.doubleSpinBox_tres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_tres.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_tres.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_tres.setSizePolicy(sizePolicy)
        self.doubleSpinBox_tres.setMinimumSize(QtCore.QSize(101, 29))
        self.doubleSpinBox_tres.setMaximumSize(QtCore.QSize(101, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_tres.setFont(font)
        self.doubleSpinBox_tres.setDecimals(5)
        self.doubleSpinBox_tres.setMinimum(0.0)
        self.doubleSpinBox_tres.setMaximum(10000.0)
        self.doubleSpinBox_tres.setObjectName("doubleSpinBox_tres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_tres)
        self.spinBox_numx = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_numx.sizePolicy().hasHeightForWidth())
        self.spinBox_numx.setSizePolicy(sizePolicy)
        self.spinBox_numx.setMinimumSize(QtCore.QSize(101, 28))
        self.spinBox_numx.setMaximumSize(QtCore.QSize(101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numx.setFont(font)
        self.spinBox_numx.setMaximum(10000)
        self.spinBox_numx.setObjectName("spinBox_numx")
        self.verticalLayout_2.addWidget(self.spinBox_numx)
        self.spinBox_numy = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numy.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_numy.sizePolicy().hasHeightForWidth())
        self.spinBox_numy.setSizePolicy(sizePolicy)
        self.spinBox_numy.setMinimumSize(QtCore.QSize(101, 28))
        self.spinBox_numy.setMaximumSize(QtCore.QSize(101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numy.setFont(font)
        self.spinBox_numy.setMaximum(10000)
        self.spinBox_numy.setObjectName("spinBox_numy")
        self.verticalLayout_2.addWidget(self.spinBox_numy)
        self.spinBox_numz = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numz.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_numz.sizePolicy().hasHeightForWidth())
        self.spinBox_numz.setSizePolicy(sizePolicy)
        self.spinBox_numz.setMinimumSize(QtCore.QSize(101, 29))
        self.spinBox_numz.setMaximumSize(QtCore.QSize(101, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numz.setFont(font)
        self.spinBox_numz.setMaximum(10000)
        self.spinBox_numz.setObjectName("spinBox_numz")
        self.verticalLayout_2.addWidget(self.spinBox_numz)
        self.spinBox_numt = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numt.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_numt.sizePolicy().hasHeightForWidth())
        self.spinBox_numt.setSizePolicy(sizePolicy)
        self.spinBox_numt.setMinimumSize(QtCore.QSize(101, 28))
        self.spinBox_numt.setMaximumSize(QtCore.QSize(101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numt.setFont(font)
        self.spinBox_numt.setMaximum(10000)
        self.spinBox_numt.setObjectName("spinBox_numt")
        self.verticalLayout_2.addWidget(self.spinBox_numt)
        self.spinBox_numch = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numch.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_numch.sizePolicy().hasHeightForWidth())
        self.spinBox_numch.setSizePolicy(sizePolicy)
        self.spinBox_numch.setMinimumSize(QtCore.QSize(101, 28))
        self.spinBox_numch.setMaximumSize(QtCore.QSize(101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numch.setFont(font)
        self.spinBox_numch.setMaximum(9)
        self.spinBox_numch.setObjectName("spinBox_numch")
        self.verticalLayout_2.addWidget(self.spinBox_numch)
        self.comboBox_mem_chan = QtGui.QComboBox(self.centralwidget)
        self.comboBox_mem_chan.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mem_chan.sizePolicy().hasHeightForWidth())
        self.comboBox_mem_chan.setSizePolicy(sizePolicy)
        self.comboBox_mem_chan.setMinimumSize(QtCore.QSize(101, 25))
        self.comboBox_mem_chan.setMaximumSize(QtCore.QSize(101, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_mem_chan.setFont(font)
        self.comboBox_mem_chan.setObjectName("comboBox_mem_chan")
        self.verticalLayout_2.addWidget(self.comboBox_mem_chan)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.btn_save_metadata = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_metadata.sizePolicy().hasHeightForWidth())
        self.btn_save_metadata.setSizePolicy(sizePolicy)
        self.btn_save_metadata.setMinimumSize(QtCore.QSize(241, 0))
        self.btn_save_metadata.setMaximumSize(QtCore.QSize(241, 16777215))
        self.btn_save_metadata.setObjectName("btn_save_metadata")
        self.verticalLayout_3.addWidget(self.btn_save_metadata)
        self.listView = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMinimumSize(QtCore.QSize(241, 70))
        self.listView.setMaximumSize(QtCore.QSize(241, 16777215))
        self.listView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.btn_select_all = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_all.sizePolicy().hasHeightForWidth())
        self.btn_select_all.setSizePolicy(sizePolicy)
        self.btn_select_all.setMinimumSize(QtCore.QSize(251, 0))
        self.btn_select_all.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.btn_select_all.setFont(font)
        self.btn_select_all.setObjectName("btn_select_all")
        self.verticalLayout_3.addWidget(self.btn_select_all)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(13, 14, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_original_image = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_original_image.sizePolicy().hasHeightForWidth())
        self.label_original_image.setSizePolicy(sizePolicy)
        self.label_original_image.setAutoFillBackground(False)
        self.label_original_image.setText("")
        self.label_original_image.setScaledContents(True)
        self.label_original_image.setObjectName("label_original_image")
        self.verticalLayout_5.addWidget(self.label_original_image)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_segmented_image = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_segmented_image.sizePolicy().hasHeightForWidth())
        self.label_segmented_image.setSizePolicy(sizePolicy)
        self.label_segmented_image.setAutoFillBackground(False)
        self.label_segmented_image.setText("")
        self.label_segmented_image.setScaledContents(True)
        self.label_segmented_image.setObjectName("label_segmented_image")
        self.verticalLayout_4.addWidget(self.label_segmented_image)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalSlider_t = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_t.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_t.setObjectName("horizontalSlider_t")
        self.verticalLayout_7.addWidget(self.horizontalSlider_t)
        self.horizontalSlider_z = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_z.setObjectName("horizontalSlider_z")
        self.verticalLayout_7.addWidget(self.horizontalSlider_z)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_preliminary_seg = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/preiliminary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_preliminary_seg.setIcon(icon)
        self.btn_preliminary_seg.setIconSize(QtCore.QSize(35, 35))
        self.btn_preliminary_seg.setObjectName("btn_preliminary_seg")
        self.horizontalLayout_5.addWidget(self.btn_preliminary_seg)
        self.btn_seg_tool = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/seg_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_seg_tool.setIcon(icon1)
        self.btn_seg_tool.setIconSize(QtCore.QSize(35, 35))
        self.btn_seg_tool.setObjectName("btn_seg_tool")
        self.horizontalLayout_5.addWidget(self.btn_seg_tool)
        self.btn_track_tool = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/track_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_track_tool.setIcon(icon2)
        self.btn_track_tool.setIconSize(QtCore.QSize(35, 35))
        self.btn_track_tool.setObjectName("btn_track_tool")
        self.horizontalLayout_5.addWidget(self.btn_track_tool)
        self.btn_analysis = QtGui.QPushButton(self.centralwidget)
        self.btn_analysis.setIcon(icon2)
        self.btn_analysis.setIconSize(QtCore.QSize(35, 35))
        self.btn_analysis.setObjectName("btn_analysis")
        self.horizontalLayout_5.addWidget(self.btn_analysis)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_clean_seg = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clean_seg.sizePolicy().hasHeightForWidth())
        self.btn_clean_seg.setSizePolicy(sizePolicy)
        self.btn_clean_seg.setObjectName("btn_clean_seg")
        self.horizontalLayout_4.addWidget(self.btn_clean_seg)
        self.btn_set_input = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set_input.sizePolicy().hasHeightForWidth())
        self.btn_set_input.setSizePolicy(sizePolicy)
        self.btn_set_input.setObjectName("btn_set_input")
        self.horizontalLayout_4.addWidget(self.btn_set_input)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.checkBox_load_saved = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_load_saved.setObjectName("checkBox_load_saved")
        self.horizontalLayout_4.addWidget(self.checkBox_load_saved)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.checkBox_use_metric = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use_metric.sizePolicy().hasHeightForWidth())
        self.checkBox_use_metric.setSizePolicy(sizePolicy)
        self.checkBox_use_metric.setChecked(False)
        self.checkBox_use_metric.setObjectName("checkBox_use_metric")
        self.horizontalLayout_4.addWidget(self.checkBox_use_metric)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.checkBox_propagate = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_propagate.setEnabled(True)
        self.checkBox_propagate.setChecked(False)
        self.checkBox_propagate.setObjectName("checkBox_propagate")
        self.horizontalLayout_4.addWidget(self.checkBox_propagate)
        self.radioButton_forward = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_forward.setChecked(True)
        self.radioButton_forward.setObjectName("radioButton_forward")
        self.horizontalLayout_4.addWidget(self.radioButton_forward)
        self.radioButton_backward = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_backward.setObjectName("radioButton_backward")
        self.horizontalLayout_4.addWidget(self.radioButton_backward)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 27))
        self.menubar.setObjectName("menubar")
        self.menuWorkspace = QtGui.QMenu(self.menubar)
        self.menuWorkspace.setObjectName("menuWorkspace")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAbout_2 = QtGui.QMenu(self.menuAbout)
        self.menuAbout_2.setObjectName("menuAbout_2")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(60, 60))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Workspace = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/1376909654_folder_starred.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Workspace.setIcon(icon3)
        self.actionNew_Workspace.setObjectName("actionNew_Workspace")
        self.actionOpen_Workspace = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/folder_full.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Workspace.setIcon(icon4)
        self.actionOpen_Workspace.setObjectName("actionOpen_Workspace")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/1376909512_bullet_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/1376909581_comment_error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/1376909502_bullet_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.actionGitHub_Repo = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/note_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitHub_Repo.setIcon(icon8)
        self.actionGitHub_Repo.setObjectName("actionGitHub_Repo")
        self.actionRun_Segmentation_Tool = QtGui.QAction(MainWindow)
        self.actionRun_Segmentation_Tool.setIcon(icon1)
        self.actionRun_Segmentation_Tool.setObjectName("actionRun_Segmentation_Tool")
        self.actionRun_Tracking_Tool = QtGui.QAction(MainWindow)
        self.actionRun_Tracking_Tool.setIcon(icon2)
        self.actionRun_Tracking_Tool.setObjectName("actionRun_Tracking_Tool")
        self.actionPreliminary_Segmentation = QtGui.QAction(MainWindow)
        self.actionPreliminary_Segmentation.setIcon(icon)
        self.actionPreliminary_Segmentation.setObjectName("actionPreliminary_Segmentation")
        self.actionAppend_Workspace = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/1376909673_folders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAppend_Workspace.setIcon(icon9)
        self.actionAppend_Workspace.setObjectName("actionAppend_Workspace")
        self.actionAnalysis_2 = QtGui.QAction(MainWindow)
        self.actionAnalysis_2.setIcon(icon2)
        self.actionAnalysis_2.setObjectName("actionAnalysis_2")
        self.menuWorkspace.addAction(self.actionNew_Workspace)
        self.menuWorkspace.addAction(self.actionOpen_Workspace)
        self.menuWorkspace.addAction(self.actionAppend_Workspace)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.actionPreliminary_Segmentation)
        self.menuWorkspace.addAction(self.actionRun_Segmentation_Tool)
        self.menuWorkspace.addAction(self.actionRun_Tracking_Tool)
        self.menuWorkspace.addAction(self.actionAnalysis_2)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.actionExit)
        self.menuAbout_2.addAction(self.actionAbout)
        self.menuAbout_2.addAction(self.actionGitHub_Repo)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.menuAbout_2.menuAction())
        self.menubar.addAction(self.menuWorkspace.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNew_Workspace)
        self.toolBar.addAction(self.actionOpen_Workspace)
        self.toolBar.addAction(self.actionAppend_Workspace)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreliminary_Segmentation)
        self.toolBar.addAction(self.actionRun_Segmentation_Tool)
        self.toolBar.addAction(self.actionRun_Tracking_Tool)
        self.toolBar.addAction(self.actionAnalysis_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionGitHub_Repo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CellECT: Cell Evolution Capturing Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "X-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Y-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Z-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "T-Resolution (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Number X units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Number Y units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Number Z units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Number T units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Number Channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Membrane Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_metadata.setText(QtGui.QApplication.translate("MainWindow", "Save metadata file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_all.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Original image preview:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Segmentation preview (if available):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Navigate time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Navigate z-depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_preliminary_seg.setText(QtGui.QApplication.translate("MainWindow", "Non-interactive Seg", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_seg_tool.setText(QtGui.QApplication.translate("MainWindow", "Interactive Seg", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_track_tool.setText(QtGui.QApplication.translate("MainWindow", "Cell Lineage", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_analysis.setText(QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clean_seg.setText(QtGui.QApplication.translate("MainWindow", "Clean Seg", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_set_input.setText(QtGui.QApplication.translate("MainWindow", "Set Input", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_load_saved.setText(QtGui.QApplication.translate("MainWindow", "Load saved", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_use_metric.setText(QtGui.QApplication.translate("MainWindow", "Use cellness metric", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_propagate.setText(QtGui.QApplication.translate("MainWindow", "Propagate corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_forward.setText(QtGui.QApplication.translate("MainWindow", "forward", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_backward.setText(QtGui.QApplication.translate("MainWindow", "backward", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWorkspace.setTitle(QtGui.QApplication.translate("MainWindow", "Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About CellECT", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout_2.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Workspace.setText(QtGui.QApplication.translate("MainWindow", "New Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Workspace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Workspace.setText(QtGui.QApplication.translate("MainWindow", "Open Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Workspace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGitHub_Repo.setText(QtGui.QApplication.translate("MainWindow", "GitHub Repo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Segmentation_Tool.setText(QtGui.QApplication.translate("MainWindow", "Interactive Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Tracking_Tool.setText(QtGui.QApplication.translate("MainWindow", "CellLineage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreliminary_Segmentation.setText(QtGui.QApplication.translate("MainWindow", "Non-interactive Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppend_Workspace.setText(QtGui.QApplication.translate("MainWindow", "Append Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppend_Workspace.setToolTip(QtGui.QApplication.translate("MainWindow", "Append Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnalysis_2.setText(QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))

import app_icons_rc
import app_resources_rc
