# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created: Thu Jan 30 18:26:12 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1407, 879)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 171, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 410, 211, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 201, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_t = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_t.setGeometry(QtCore.QRect(413, 630, 981, 29))
        self.horizontalSlider_t.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_t.setObjectName("horizontalSlider_t")
        self.horizontalSlider_z = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_z.setGeometry(QtCore.QRect(413, 660, 981, 29))
        self.horizontalSlider_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_z.setObjectName("horizontalSlider_z")
        self.btn_preliminary_seg = QtGui.QPushButton(self.centralwidget)
        self.btn_preliminary_seg.setGeometry(QtCore.QRect(273, 700, 361, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/preiliminary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_preliminary_seg.setIcon(icon)
        self.btn_preliminary_seg.setIconSize(QtCore.QSize(35, 35))
        self.btn_preliminary_seg.setObjectName("btn_preliminary_seg")
        self.btn_seg_tool = QtGui.QPushButton(self.centralwidget)
        self.btn_seg_tool.setGeometry(QtCore.QRect(650, 700, 361, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/seg_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_seg_tool.setIcon(icon1)
        self.btn_seg_tool.setIconSize(QtCore.QSize(35, 35))
        self.btn_seg_tool.setObjectName("btn_seg_tool")
        self.btn_track_tool = QtGui.QPushButton(self.centralwidget)
        self.btn_track_tool.setGeometry(QtCore.QRect(1030, 700, 361, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/track_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_track_tool.setIcon(icon2)
        self.btn_track_tool.setIconSize(QtCore.QSize(35, 35))
        self.btn_track_tool.setObjectName("btn_track_tool")
        self.label_original_image = QtGui.QLabel(self.centralwidget)
        self.label_original_image.setGeometry(QtCore.QRect(283, 50, 541, 561))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_original_image.sizePolicy().hasHeightForWidth())
        self.label_original_image.setSizePolicy(sizePolicy)
        self.label_original_image.setAutoFillBackground(True)
        self.label_original_image.setText("")
        self.label_original_image.setScaledContents(True)
        self.label_original_image.setObjectName("label_original_image")
        self.label_segmented_image = QtGui.QLabel(self.centralwidget)
        self.label_segmented_image.setGeometry(QtCore.QRect(850, 50, 541, 561))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_segmented_image.sizePolicy().hasHeightForWidth())
        self.label_segmented_image.setSizePolicy(sizePolicy)
        self.label_segmented_image.setAutoFillBackground(True)
        self.label_segmented_image.setText("")
        self.label_segmented_image.setScaledContents(True)
        self.label_segmented_image.setObjectName("label_segmented_image")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(850, 20, 351, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_select_all = QtGui.QPushButton(self.centralwidget)
        self.btn_select_all.setGeometry(QtCore.QRect(20, 680, 231, 27))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.btn_select_all.setFont(font)
        self.btn_select_all.setObjectName("btn_select_all")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 637, 101, 17))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 666, 121, 17))
        self.label_6.setObjectName("label_6")
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 440, 231, 231))
        self.listView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView.setObjectName("listView")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 151, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 151, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 151, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 150, 141, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 180, 111, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 210, 111, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 240, 111, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 270, 111, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 300, 121, 17))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 330, 141, 17))
        self.label_17.setObjectName("label_17")
        self.btn_save_metadata = QtGui.QPushButton(self.centralwidget)
        self.btn_save_metadata.setGeometry(QtCore.QRect(20, 370, 231, 27))
        self.btn_save_metadata.setObjectName("btn_save_metadata")
        self.doubleSpinBox_xres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_xres.setEnabled(False)
        self.doubleSpinBox_xres.setGeometry(QtCore.QRect(160, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_xres.setFont(font)
        self.doubleSpinBox_xres.setDecimals(5)
        self.doubleSpinBox_xres.setMinimum(0.0)
        self.doubleSpinBox_xres.setMaximum(10000000.0)
        self.doubleSpinBox_xres.setProperty("value", 1.0)
        self.doubleSpinBox_xres.setObjectName("doubleSpinBox_xres")
        self.doubleSpinBox_yres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_yres.setEnabled(False)
        self.doubleSpinBox_yres.setGeometry(QtCore.QRect(160, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_yres.setFont(font)
        self.doubleSpinBox_yres.setDecimals(5)
        self.doubleSpinBox_yres.setMinimum(0.0)
        self.doubleSpinBox_yres.setMaximum(10000000.0)
        self.doubleSpinBox_yres.setProperty("value", 1.0)
        self.doubleSpinBox_yres.setObjectName("doubleSpinBox_yres")
        self.doubleSpinBox_zres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_zres.setEnabled(False)
        self.doubleSpinBox_zres.setGeometry(QtCore.QRect(160, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_zres.setFont(font)
        self.doubleSpinBox_zres.setDecimals(5)
        self.doubleSpinBox_zres.setMinimum(0.0)
        self.doubleSpinBox_zres.setMaximum(10000000.0)
        self.doubleSpinBox_zres.setProperty("value", 1.0)
        self.doubleSpinBox_zres.setObjectName("doubleSpinBox_zres")
        self.doubleSpinBox_tres = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_tres.setEnabled(False)
        self.doubleSpinBox_tres.setGeometry(QtCore.QRect(160, 150, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_tres.setFont(font)
        self.doubleSpinBox_tres.setDecimals(5)
        self.doubleSpinBox_tres.setMinimum(0.0)
        self.doubleSpinBox_tres.setMaximum(10000.0)
        self.doubleSpinBox_tres.setSingleStep(1.0)
        self.doubleSpinBox_tres.setProperty("value", 1.0)
        self.doubleSpinBox_tres.setObjectName("doubleSpinBox_tres")
        self.comboBox_mem_chan = QtGui.QComboBox(self.centralwidget)
        self.comboBox_mem_chan.setEnabled(False)
        self.comboBox_mem_chan.setGeometry(QtCore.QRect(160, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_mem_chan.setFont(font)
        self.comboBox_mem_chan.setObjectName("comboBox_mem_chan")
        self.spinBox_numx = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numx.setEnabled(False)
        self.spinBox_numx.setGeometry(QtCore.QRect(160, 180, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numx.setFont(font)
        self.spinBox_numx.setMaximum(10000)
        self.spinBox_numx.setObjectName("spinBox_numx")
        self.spinBox_numy = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numy.setEnabled(False)
        self.spinBox_numy.setGeometry(QtCore.QRect(160, 210, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numy.setFont(font)
        self.spinBox_numy.setMaximum(10000)
        self.spinBox_numy.setObjectName("spinBox_numy")
        self.spinBox_numz = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numz.setEnabled(False)
        self.spinBox_numz.setGeometry(QtCore.QRect(160, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numz.setFont(font)
        self.spinBox_numz.setMaximum(10000)
        self.spinBox_numz.setObjectName("spinBox_numz")
        self.spinBox_numt = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numt.setEnabled(False)
        self.spinBox_numt.setGeometry(QtCore.QRect(160, 270, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numt.setFont(font)
        self.spinBox_numt.setMaximum(10000)
        self.spinBox_numt.setObjectName("spinBox_numt")
        self.spinBox_numch = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_numch.setEnabled(False)
        self.spinBox_numch.setGeometry(QtCore.QRect(160, 300, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numch.setFont(font)
        self.spinBox_numch.setMaximum(9)
        self.spinBox_numch.setObjectName("spinBox_numch")
        self.checkBox_use_metric = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_use_metric.setGeometry(QtCore.QRect(30, 720, 231, 22))
        self.checkBox_use_metric.setChecked(True)
        self.checkBox_use_metric.setObjectName("checkBox_use_metric")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1407, 27))
        self.menubar.setObjectName("menubar")
        self.menuWorkspace = QtGui.QMenu(self.menubar)
        self.menuWorkspace.setObjectName("menuWorkspace")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAbout_2 = QtGui.QMenu(self.menuAbout)
        self.menuAbout_2.setObjectName("menuAbout_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(60, 60))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Workspace = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/1376909654_folder_starred.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Workspace.setIcon(icon3)
        self.actionNew_Workspace.setObjectName("actionNew_Workspace")
        self.actionOpen_Workspace = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/folder_full.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Workspace.setIcon(icon4)
        self.actionOpen_Workspace.setObjectName("actionOpen_Workspace")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/1376909512_bullet_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/1376909581_comment_error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/1376909502_bullet_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.actionGitHub_Repo = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/note_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitHub_Repo.setIcon(icon8)
        self.actionGitHub_Repo.setObjectName("actionGitHub_Repo")
        self.actionRun_Segmentation_Tool = QtGui.QAction(MainWindow)
        self.actionRun_Segmentation_Tool.setIcon(icon1)
        self.actionRun_Segmentation_Tool.setObjectName("actionRun_Segmentation_Tool")
        self.actionRun_Tracking_Tool = QtGui.QAction(MainWindow)
        self.actionRun_Tracking_Tool.setIcon(icon2)
        self.actionRun_Tracking_Tool.setObjectName("actionRun_Tracking_Tool")
        self.actionPreliminary_Segmentation = QtGui.QAction(MainWindow)
        self.actionPreliminary_Segmentation.setIcon(icon)
        self.actionPreliminary_Segmentation.setObjectName("actionPreliminary_Segmentation")
        self.actionAppend_Workspace = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/1376909673_folders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAppend_Workspace.setIcon(icon9)
        self.actionAppend_Workspace.setObjectName("actionAppend_Workspace")
        self.menuWorkspace.addAction(self.actionNew_Workspace)
        self.menuWorkspace.addAction(self.actionOpen_Workspace)
        self.menuWorkspace.addAction(self.actionAppend_Workspace)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.actionPreliminary_Segmentation)
        self.menuWorkspace.addAction(self.actionRun_Segmentation_Tool)
        self.menuWorkspace.addAction(self.actionRun_Tracking_Tool)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.actionExit)
        self.menuAbout_2.addAction(self.actionAbout)
        self.menuAbout_2.addAction(self.actionGitHub_Repo)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.menuAbout_2.menuAction())
        self.menubar.addAction(self.menuWorkspace.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNew_Workspace)
        self.toolBar.addAction(self.actionOpen_Workspace)
        self.toolBar.addAction(self.actionAppend_Workspace)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreliminary_Segmentation)
        self.toolBar.addAction(self.actionRun_Segmentation_Tool)
        self.toolBar.addAction(self.actionRun_Tracking_Tool)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionGitHub_Repo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CellECT: Cell Evolution Capturing Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Dataset information:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Segmentation checklist:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Original image preview:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_preliminary_seg.setText(QtGui.QApplication.translate("MainWindow", "Preliminary Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_seg_tool.setText(QtGui.QApplication.translate("MainWindow", "Run Segmentation Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_track_tool.setText(QtGui.QApplication.translate("MainWindow", "Run Tracking Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Segmentation preview (if available):", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_all.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Navigate time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Navigate z-depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "X-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Y-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Z-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "T-Resolution (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Number X units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Number Y units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Number Z units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Number T units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Number Channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Membrane Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_metadata.setText(QtGui.QApplication.translate("MainWindow", "Save metadata file", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_use_metric.setText(QtGui.QApplication.translate("MainWindow", "use cellness metric", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWorkspace.setTitle(QtGui.QApplication.translate("MainWindow", "Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About CellECT", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout_2.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Workspace.setText(QtGui.QApplication.translate("MainWindow", "New Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Workspace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Workspace.setText(QtGui.QApplication.translate("MainWindow", "Open Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Workspace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGitHub_Repo.setText(QtGui.QApplication.translate("MainWindow", "GitHub Repo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Segmentation_Tool.setText(QtGui.QApplication.translate("MainWindow", "Run Segmentation Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Tracking_Tool.setText(QtGui.QApplication.translate("MainWindow", "Run Tracking Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreliminary_Segmentation.setText(QtGui.QApplication.translate("MainWindow", "Preliminary Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppend_Workspace.setText(QtGui.QApplication.translate("MainWindow", "Append Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppend_Workspace.setToolTip(QtGui.QApplication.translate("MainWindow", "Append Workspace", None, QtGui.QApplication.UnicodeUTF8))

import app_icons_rc
import app_resources_rc
