# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_workspace_layout.ui'
#
# Created: Sun Aug 25 14:39:14 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(587, 763)
        self.btn_select_img = QtGui.QPushButton(Dialog)
        self.btn_select_img.setGeometry(QtCore.QRect(30, 50, 161, 41))
        self.btn_select_img.setObjectName("btn_select_img")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 200, 271, 271))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 540, 251, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 540, 171, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 550, 21, 21))
        self.label_2.setObjectName("label_2")
        self.brn_load_metadata = QtGui.QPushButton(Dialog)
        self.brn_load_metadata.setGeometry(QtCore.QRect(30, 140, 161, 41))
        self.brn_load_metadata.setObjectName("brn_load_metadata")
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 290, 141, 17))
        self.label_10.setObjectName("label_10")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 230, 151, 17))
        self.label_8.setObjectName("label_8")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(40, 410, 111, 17))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 320, 111, 17))
        self.label_11.setObjectName("label_11")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 200, 151, 17))
        self.label_7.setObjectName("label_7")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(40, 440, 121, 17))
        self.label_15.setObjectName("label_15")
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 350, 111, 17))
        self.label_12.setObjectName("label_12")
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 260, 151, 17))
        self.label_9.setObjectName("label_9")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(40, 470, 141, 17))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(40, 380, 111, 17))
        self.label_13.setObjectName("label_13")
        self.doubleSpinBox_yres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_yres.setGeometry(QtCore.QRect(180, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_yres.setFont(font)
        self.doubleSpinBox_yres.setObjectName("doubleSpinBox_yres")
        self.spinBox_numt = QtGui.QSpinBox(Dialog)
        self.spinBox_numt.setGeometry(QtCore.QRect(180, 410, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numt.setFont(font)
        self.spinBox_numt.setMaximum(10000)
        self.spinBox_numt.setObjectName("spinBox_numt")
        self.doubleSpinBox_xres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_xres.setGeometry(QtCore.QRect(180, 200, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_xres.setFont(font)
        self.doubleSpinBox_xres.setObjectName("doubleSpinBox_xres")
        self.spinBox_numch = QtGui.QSpinBox(Dialog)
        self.spinBox_numch.setGeometry(QtCore.QRect(180, 440, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numch.setFont(font)
        self.spinBox_numch.setObjectName("spinBox_numch")
        self.spinBox_numz = QtGui.QSpinBox(Dialog)
        self.spinBox_numz.setGeometry(QtCore.QRect(180, 380, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numz.setFont(font)
        self.spinBox_numz.setMaximum(10000)
        self.spinBox_numz.setObjectName("spinBox_numz")
        self.comboBox_mem_chan = QtGui.QComboBox(Dialog)
        self.comboBox_mem_chan.setGeometry(QtCore.QRect(180, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_mem_chan.setFont(font)
        self.comboBox_mem_chan.setObjectName("comboBox_mem_chan")
        self.spinBox_numy = QtGui.QSpinBox(Dialog)
        self.spinBox_numy.setGeometry(QtCore.QRect(180, 350, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numy.setFont(font)
        self.spinBox_numy.setMaximum(10000)
        self.spinBox_numy.setObjectName("spinBox_numy")
        self.spinBox_numx = QtGui.QSpinBox(Dialog)
        self.spinBox_numx.setGeometry(QtCore.QRect(180, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numx.setFont(font)
        self.spinBox_numx.setMaximum(10000)
        self.spinBox_numx.setObjectName("spinBox_numx")
        self.doubleSpinBox_zres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_zres.setGeometry(QtCore.QRect(180, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_zres.setFont(font)
        self.doubleSpinBox_zres.setObjectName("doubleSpinBox_zres")
        self.doubleSpinBox_tres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_tres.setGeometry(QtCore.QRect(180, 290, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_tres.setFont(font)
        self.doubleSpinBox_tres.setMaximum(10000.0)
        self.doubleSpinBox_tres.setObjectName("doubleSpinBox_tres")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 451, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 411, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 510, 471, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_create_ws = QtGui.QPushButton(Dialog)
        self.btn_create_ws.setGeometry(QtCore.QRect(160, 710, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.btn_create_ws.setFont(font)
        self.btn_create_ws.setObjectName("btn_create_ws")
        self.btn_cancel = QtGui.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(350, 710, 81, 41))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(30, 600, 471, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.btnn_choose_location = QtGui.QPushButton(Dialog)
        self.btnn_choose_location.setGeometry(QtCore.QRect(410, 620, 131, 41))
        self.btnn_choose_location.setObjectName("btnn_choose_location")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(40, 640, 131, 21))
        self.label_19.setObjectName("label_19")
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(170, 630, 191, 33))
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 680, 541, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "New Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_img.setText(QtGui.QApplication.translate("Dialog", "Select 4D stack", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Select Nuclear Detector Output", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Make Input Seeds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.brn_load_metadata.setText(QtGui.QApplication.translate("Dialog", "Load metadata file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "T-Resolution (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Y-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Number T units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Number X units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "X-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Number Channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Number Y units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Z-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Membrane Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Number Z units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Step 1: Select a 3D or 4D tiff stack.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Step 2: Fill in or load .csv file with medata.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Step 3: Select nuclei detector out file or make your own seeds.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create_ws.setText(QtGui.QApplication.translate("Dialog", "Create workspace!", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Step 4: Name the workspace and choose location.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnn_choose_location.setText(QtGui.QApplication.translate("Dialog", "Choose location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Workspace name:", None, QtGui.QApplication.UnicodeUTF8))

