# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_workspace_layout.ui'
#
# Created: Tue May 27 12:45:25 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(747, 489)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_select_img = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_img.sizePolicy().hasHeightForWidth())
        self.btn_select_img.setSizePolicy(sizePolicy)
        self.btn_select_img.setObjectName("btn_select_img")
        self.verticalLayout_3.addWidget(self.btn_select_img)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.label_preview_img = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preview_img.sizePolicy().hasHeightForWidth())
        self.label_preview_img.setSizePolicy(sizePolicy)
        self.label_preview_img.setMinimumSize(QtCore.QSize(30, 30))
        self.label_preview_img.setAutoFillBackground(True)
        self.label_preview_img.setText("")
        self.label_preview_img.setScaledContents(True)
        self.label_preview_img.setObjectName("label_preview_img")
        self.horizontalLayout_4.addWidget(self.label_preview_img)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_load_metadata_csv = QtGui.QPushButton(Dialog)
        self.btn_load_metadata_csv.setObjectName("btn_load_metadata_csv")
        self.horizontalLayout_2.addWidget(self.btn_load_metadata_csv)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.btn_load_metadata_xml = QtGui.QPushButton(Dialog)
        self.btn_load_metadata_xml.setObjectName("btn_load_metadata_xml")
        self.horizontalLayout_2.addWidget(self.btn_load_metadata_xml)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.btn_import_nuclei_csv = QtGui.QPushButton(Dialog)
        self.btn_import_nuclei_csv.setObjectName("btn_import_nuclei_csv")
        self.verticalLayout_4.addWidget(self.btn_import_nuclei_csv)
        self.label_18 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.lineEdit_ws_name = QtGui.QLineEdit(Dialog)
        self.lineEdit_ws_name.setObjectName("lineEdit_ws_name")
        self.horizontalLayout_3.addWidget(self.lineEdit_ws_name)
        self.btn_choose_location = QtGui.QPushButton(Dialog)
        self.btn_choose_location.setObjectName("btn_choose_location")
        self.horizontalLayout_3.addWidget(self.btn_choose_location)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doubleSpinBox_xres = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_xres.setFont(font)
        self.doubleSpinBox_xres.setDecimals(5)
        self.doubleSpinBox_xres.setMinimum(1e-05)
        self.doubleSpinBox_xres.setMaximum(100000.0)
        self.doubleSpinBox_xres.setProperty("value", 1.0)
        self.doubleSpinBox_xres.setObjectName("doubleSpinBox_xres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_xres)
        self.doubleSpinBox_yres = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_yres.setFont(font)
        self.doubleSpinBox_yres.setDecimals(5)
        self.doubleSpinBox_yres.setMinimum(1e-05)
        self.doubleSpinBox_yres.setMaximum(100000.0)
        self.doubleSpinBox_yres.setProperty("value", 1.0)
        self.doubleSpinBox_yres.setObjectName("doubleSpinBox_yres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_yres)
        self.doubleSpinBox_zres = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_zres.setFont(font)
        self.doubleSpinBox_zres.setDecimals(5)
        self.doubleSpinBox_zres.setMinimum(1e-05)
        self.doubleSpinBox_zres.setMaximum(100000.0)
        self.doubleSpinBox_zres.setProperty("value", 1.0)
        self.doubleSpinBox_zres.setObjectName("doubleSpinBox_zres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_zres)
        self.doubleSpinBox_tres = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_tres.setFont(font)
        self.doubleSpinBox_tres.setDecimals(5)
        self.doubleSpinBox_tres.setMinimum(1e-05)
        self.doubleSpinBox_tres.setMaximum(100000.0)
        self.doubleSpinBox_tres.setProperty("value", 1.0)
        self.doubleSpinBox_tres.setObjectName("doubleSpinBox_tres")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_tres)
        self.spinBox_numx = QtGui.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numx.setFont(font)
        self.spinBox_numx.setMaximum(10000)
        self.spinBox_numx.setObjectName("spinBox_numx")
        self.verticalLayout_2.addWidget(self.spinBox_numx)
        self.spinBox_numy = QtGui.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numy.setFont(font)
        self.spinBox_numy.setMaximum(10000)
        self.spinBox_numy.setObjectName("spinBox_numy")
        self.verticalLayout_2.addWidget(self.spinBox_numy)
        self.spinBox_numz = QtGui.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numz.setFont(font)
        self.spinBox_numz.setMaximum(10000)
        self.spinBox_numz.setProperty("value", 0)
        self.spinBox_numz.setObjectName("spinBox_numz")
        self.verticalLayout_2.addWidget(self.spinBox_numz)
        self.spinBox_numt = QtGui.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numt.setFont(font)
        self.spinBox_numt.setMaximum(10000)
        self.spinBox_numt.setProperty("value", 0)
        self.spinBox_numt.setObjectName("spinBox_numt")
        self.verticalLayout_2.addWidget(self.spinBox_numt)
        self.spinBox_numch = QtGui.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numch.setFont(font)
        self.spinBox_numch.setMaximum(9)
        self.spinBox_numch.setProperty("value", 0)
        self.spinBox_numch.setObjectName("spinBox_numch")
        self.verticalLayout_2.addWidget(self.spinBox_numch)
        self.comboBox_mem_chan = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_mem_chan.setFont(font)
        self.comboBox_mem_chan.setObjectName("comboBox_mem_chan")
        self.verticalLayout_2.addWidget(self.comboBox_mem_chan)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.btn_create_ws = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.btn_create_ws.setFont(font)
        self.btn_create_ws.setObjectName("btn_create_ws")
        self.horizontalLayout_5.addWidget(self.btn_create_ws)
        self.btn_cancel = QtGui.QPushButton(Dialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_5.addWidget(self.btn_cancel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_5.addWidget(self.progressBar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_select_img, self.btn_load_metadata_csv)
        Dialog.setTabOrder(self.btn_load_metadata_csv, self.btn_load_metadata_xml)
        Dialog.setTabOrder(self.btn_load_metadata_xml, self.doubleSpinBox_xres)
        Dialog.setTabOrder(self.doubleSpinBox_xres, self.doubleSpinBox_yres)
        Dialog.setTabOrder(self.doubleSpinBox_yres, self.doubleSpinBox_zres)
        Dialog.setTabOrder(self.doubleSpinBox_zres, self.doubleSpinBox_tres)
        Dialog.setTabOrder(self.doubleSpinBox_tres, self.spinBox_numx)
        Dialog.setTabOrder(self.spinBox_numx, self.spinBox_numy)
        Dialog.setTabOrder(self.spinBox_numy, self.spinBox_numz)
        Dialog.setTabOrder(self.spinBox_numz, self.spinBox_numt)
        Dialog.setTabOrder(self.spinBox_numt, self.spinBox_numch)
        Dialog.setTabOrder(self.spinBox_numch, self.comboBox_mem_chan)
        Dialog.setTabOrder(self.comboBox_mem_chan, self.btn_import_nuclei_csv)
        Dialog.setTabOrder(self.btn_import_nuclei_csv, self.lineEdit_ws_name)
        Dialog.setTabOrder(self.lineEdit_ws_name, self.btn_choose_location)
        Dialog.setTabOrder(self.btn_choose_location, self.btn_create_ws)
        Dialog.setTabOrder(self.btn_create_ws, self.btn_cancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "New Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Step 1: Select a 3D or 4D tiff stack.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_img.setText(QtGui.QApplication.translate("Dialog", "Select 4D stack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Step 2: Verify, fill in or load file with medata.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_metadata_csv.setText(QtGui.QApplication.translate("Dialog", "Load metadata CSV file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_metadata_xml.setText(QtGui.QApplication.translate("Dialog", "Load metadata XML file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Step 3: Select nuclei detector results file. (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_import_nuclei_csv.setText(QtGui.QApplication.translate("Dialog", "Import nuclei locations .CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Step 4: Name the workspace and choose location.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Workspace name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_location.setText(QtGui.QApplication.translate("Dialog", "Choose location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "X-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Y-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Z-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "T-Resolution (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Number X units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Number Y units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Number Z units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Number T units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Number Channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Membrane Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create_ws.setText(QtGui.QApplication.translate("Dialog", "Create workspace!", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

