# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_workspace_layout.ui'
#
# Created: Sun Mar 30 22:20:37 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(584, 802)
        self.btn_select_img = QtGui.QPushButton(Dialog)
        self.btn_select_img.setGeometry(QtCore.QRect(20, 50, 161, 41))
        self.btn_select_img.setObjectName("btn_select_img")
        self.label_preview_img = QtGui.QLabel(Dialog)
        self.label_preview_img.setGeometry(QtCore.QRect(280, 210, 271, 271))
        self.label_preview_img.setAutoFillBackground(True)
        self.label_preview_img.setText("")
        self.label_preview_img.setScaledContents(True)
        self.label_preview_img.setObjectName("label_preview_img")
        self.btn_import_nuclei_csv = QtGui.QPushButton(Dialog)
        self.btn_import_nuclei_csv.setGeometry(QtCore.QRect(20, 540, 251, 41))
        self.btn_import_nuclei_csv.setObjectName("btn_import_nuclei_csv")
        self.btn_load_metadata_csv = QtGui.QPushButton(Dialog)
        self.btn_load_metadata_csv.setGeometry(QtCore.QRect(20, 140, 171, 41))
        self.btn_load_metadata_csv.setObjectName("btn_load_metadata_csv")
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(30, 290, 141, 17))
        self.label_10.setObjectName("label_10")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 230, 151, 17))
        self.label_8.setObjectName("label_8")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(30, 410, 111, 17))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 320, 111, 17))
        self.label_11.setObjectName("label_11")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 151, 17))
        self.label_7.setObjectName("label_7")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(30, 440, 121, 17))
        self.label_15.setObjectName("label_15")
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(30, 350, 111, 17))
        self.label_12.setObjectName("label_12")
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 260, 151, 17))
        self.label_9.setObjectName("label_9")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(30, 470, 141, 17))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 380, 111, 17))
        self.label_13.setObjectName("label_13")
        self.doubleSpinBox_yres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_yres.setGeometry(QtCore.QRect(170, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_yres.setFont(font)
        self.doubleSpinBox_yres.setDecimals(5)
        self.doubleSpinBox_yres.setMinimum(1e-05)
        self.doubleSpinBox_yres.setMaximum(100000.0)
        self.doubleSpinBox_yres.setProperty("value", 1.0)
        self.doubleSpinBox_yres.setObjectName("doubleSpinBox_yres")
        self.spinBox_numt = QtGui.QSpinBox(Dialog)
        self.spinBox_numt.setGeometry(QtCore.QRect(170, 410, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numt.setFont(font)
        self.spinBox_numt.setMaximum(10000)
        self.spinBox_numt.setProperty("value", 0)
        self.spinBox_numt.setObjectName("spinBox_numt")
        self.doubleSpinBox_xres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_xres.setGeometry(QtCore.QRect(170, 200, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_xres.setFont(font)
        self.doubleSpinBox_xres.setDecimals(5)
        self.doubleSpinBox_xres.setMinimum(1e-05)
        self.doubleSpinBox_xres.setMaximum(100000.0)
        self.doubleSpinBox_xres.setProperty("value", 1.0)
        self.doubleSpinBox_xres.setObjectName("doubleSpinBox_xres")
        self.spinBox_numch = QtGui.QSpinBox(Dialog)
        self.spinBox_numch.setGeometry(QtCore.QRect(170, 440, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numch.setFont(font)
        self.spinBox_numch.setMaximum(9)
        self.spinBox_numch.setProperty("value", 0)
        self.spinBox_numch.setObjectName("spinBox_numch")
        self.spinBox_numz = QtGui.QSpinBox(Dialog)
        self.spinBox_numz.setGeometry(QtCore.QRect(170, 380, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numz.setFont(font)
        self.spinBox_numz.setMaximum(10000)
        self.spinBox_numz.setProperty("value", 0)
        self.spinBox_numz.setObjectName("spinBox_numz")
        self.comboBox_mem_chan = QtGui.QComboBox(Dialog)
        self.comboBox_mem_chan.setGeometry(QtCore.QRect(170, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_mem_chan.setFont(font)
        self.comboBox_mem_chan.setObjectName("comboBox_mem_chan")
        self.spinBox_numy = QtGui.QSpinBox(Dialog)
        self.spinBox_numy.setGeometry(QtCore.QRect(170, 350, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numy.setFont(font)
        self.spinBox_numy.setMaximum(10000)
        self.spinBox_numy.setObjectName("spinBox_numy")
        self.spinBox_numx = QtGui.QSpinBox(Dialog)
        self.spinBox_numx.setGeometry(QtCore.QRect(170, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.spinBox_numx.setFont(font)
        self.spinBox_numx.setMaximum(10000)
        self.spinBox_numx.setObjectName("spinBox_numx")
        self.doubleSpinBox_zres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_zres.setGeometry(QtCore.QRect(170, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_zres.setFont(font)
        self.doubleSpinBox_zres.setDecimals(5)
        self.doubleSpinBox_zres.setMinimum(1e-05)
        self.doubleSpinBox_zres.setMaximum(100000.0)
        self.doubleSpinBox_zres.setProperty("value", 1.0)
        self.doubleSpinBox_zres.setObjectName("doubleSpinBox_zres")
        self.doubleSpinBox_tres = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_tres.setGeometry(QtCore.QRect(170, 290, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.doubleSpinBox_tres.setFont(font)
        self.doubleSpinBox_tres.setDecimals(5)
        self.doubleSpinBox_tres.setMinimum(1e-05)
        self.doubleSpinBox_tres.setMaximum(100000.0)
        self.doubleSpinBox_tres.setProperty("value", 1.0)
        self.doubleSpinBox_tres.setObjectName("doubleSpinBox_tres")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 451, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 411, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 510, 471, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_create_ws = QtGui.QPushButton(Dialog)
        self.btn_create_ws.setGeometry(QtCore.QRect(150, 710, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.btn_create_ws.setFont(font)
        self.btn_create_ws.setObjectName("btn_create_ws")
        self.btn_cancel = QtGui.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(340, 710, 81, 41))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(20, 600, 471, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.btn_choose_location = QtGui.QPushButton(Dialog)
        self.btn_choose_location.setGeometry(QtCore.QRect(400, 620, 131, 41))
        self.btn_choose_location.setObjectName("btn_choose_location")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(30, 640, 131, 21))
        self.label_19.setObjectName("label_19")
        self.lineEdit_ws_name = QtGui.QLineEdit(Dialog)
        self.lineEdit_ws_name.setGeometry(QtCore.QRect(160, 630, 191, 33))
        self.lineEdit_ws_name.setObjectName("lineEdit_ws_name")
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 680, 541, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 770, 561, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btn_load_metadata_xml = QtGui.QPushButton(Dialog)
        self.btn_load_metadata_xml.setGeometry(QtCore.QRect(240, 140, 181, 41))
        self.btn_load_metadata_xml.setObjectName("btn_load_metadata_xml")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 150, 21, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_select_img, self.btn_load_metadata_csv)
        Dialog.setTabOrder(self.btn_load_metadata_csv, self.btn_load_metadata_xml)
        Dialog.setTabOrder(self.btn_load_metadata_xml, self.doubleSpinBox_xres)
        Dialog.setTabOrder(self.doubleSpinBox_xres, self.doubleSpinBox_yres)
        Dialog.setTabOrder(self.doubleSpinBox_yres, self.doubleSpinBox_zres)
        Dialog.setTabOrder(self.doubleSpinBox_zres, self.doubleSpinBox_tres)
        Dialog.setTabOrder(self.doubleSpinBox_tres, self.spinBox_numx)
        Dialog.setTabOrder(self.spinBox_numx, self.spinBox_numy)
        Dialog.setTabOrder(self.spinBox_numy, self.spinBox_numz)
        Dialog.setTabOrder(self.spinBox_numz, self.spinBox_numt)
        Dialog.setTabOrder(self.spinBox_numt, self.spinBox_numch)
        Dialog.setTabOrder(self.spinBox_numch, self.comboBox_mem_chan)
        Dialog.setTabOrder(self.comboBox_mem_chan, self.btn_import_nuclei_csv)
        Dialog.setTabOrder(self.btn_import_nuclei_csv, self.lineEdit_ws_name)
        Dialog.setTabOrder(self.lineEdit_ws_name, self.btn_choose_location)
        Dialog.setTabOrder(self.btn_choose_location, self.btn_create_ws)
        Dialog.setTabOrder(self.btn_create_ws, self.btn_cancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "New Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_img.setText(QtGui.QApplication.translate("Dialog", "Select 4D stack", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_import_nuclei_csv.setText(QtGui.QApplication.translate("Dialog", "Import nuclei locations .CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_metadata_csv.setText(QtGui.QApplication.translate("Dialog", "Load metadata CSV file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "T-Resolution (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Y-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Number T units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Number X units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "X-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Number Channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Number Y units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Z-Resolution (µm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Membrane Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Number Z units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Step 1: Select a 3D or 4D tiff stack.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Step 2: Verify, fill in or load file with medata.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Step 3: Select nuclei detector results file. (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create_ws.setText(QtGui.QApplication.translate("Dialog", "Create workspace!", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Step 4: Name the workspace and choose location.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choose_location.setText(QtGui.QApplication.translate("Dialog", "Choose location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Workspace name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_metadata_xml.setText(QtGui.QApplication.translate("Dialog", "Load metadata XML file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "or", None, QtGui.QApplication.UnicodeUTF8))

