#!/usr/bin/env python

# Author: Diana Delibaltov
# Vision Research Lab, University of California Santa Barbara

# Module information
import CellECT.track_tool.module_info


# Imports
import pdb
import logging
import datetime
import sys
from termcolor import colored

#import numpy as np
#import scipy as sp
#import interactive_seg as iseg
#import pdb
#import xml.etree.ElementTree as ET
#import copy
#import pylab
#from pygraph.classes.digraph import digraph
#from pygraph.algorithms.accessibility import connected_components
#from numpy import random
#import re
#import sys
#from openopt import LP


# Imports from this project
from CellECT.track_tool.track_io import load_parameters
from CellECT.track_tool.cell_tracker_core import load_tracker
from CellECT.track_tool.gui import cell_tracker_ui as ctui
import CellECT.track_tool.cell_tracker_core.tracklet_connector as tc


def setup_logging():

	logging.basicConfig(filename='CellECT_track_tool.log', level=logging.INFO)
	message = " =============================== Starting CellECT_track_tool ============================================"
	logging.info (message)
	logging.info('Started at %s' % datetime.datetime.now().strftime("%Y-%m-%d %H:%M") )



def ask_for_config_file():

	print colored("Please provide location of configuration file.", "red")
	import Tkinter, tkFileDialog

	root = Tkinter.Tk()
	root.withdraw()
	file_path = tkFileDialog.askopenfilename()
	root.destroy()

	return file_path



def main():

	setup_logging()
	
	## CHECK INPUT #############################################################
	if len(sys.argv) != 2:
		config_file_path = ask_for_config_file()
	else:
		config_file_path = sys.argv[1]

	print "Loading config parameters..."
	load_parameters.read_program_parameters(config_file_path)

	ct = load_tracker.load_cell_tracker()

	print "EDGES: ", len(ct.graph.edges())

	
	#ct_ui.gui_menu()

	tc.TrackletConnector(ct)

	print "EDGES: ", len(ct.graph.edges())
	ct_ui = ctui.CellTrackerUI(ct)
	ct_ui.gui_menu()



if __name__ == "__main__":

	main()

	print "KTnxBye."


