#!/usr/bin/env python

# Author: Diana Delibaltov
# Vision Research Lab, University of California Santa Barbara

import os
import sys



def main():

	print "Calling seg_tool app."

	os.system("CellECT_seg_tool " + sys.argv[1])

	print "Done."


if __name__ == "__main__":


	main()
